/// generated by ai
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct ChampSelectSession {
    pub allow_duplicate_picks: bool,
    pub allow_locked_events: bool,
    pub bench_champions: Vec<BenchChampion>,
    pub bench_enabled: bool,
    pub boostable_skin_count: i32,
    pub counter: i32,
    pub entitled_feature_state: EntitledFeatureState,
    pub game_id: i64,
    pub locked_event_index: i32,
    pub pick_order_swaps: Vec<serde_json::Value>,
    pub recovery_counter: i32,
    pub skip_champion_select: bool,
    #[serde(flatten)]
    pub base: ChampSelectSessionBase,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct ChampSelectSessionBase {
    pub actions: Vec<Vec<Action>>,
    pub allow_battle_boost: bool,
    pub allow_rerolling: bool,
    pub allow_skin_selection: bool,
    pub allow_subset_champion_picks: bool,
    pub bans: Bans,
    pub chat_details: ChatDetails,
    pub has_simultaneous_bans: bool,
    pub has_simultaneous_picks: bool,
    pub is_custom_game: bool,
    pub is_spectating: bool,
    pub local_player_cell_id: i32,
    pub my_team: Vec<ChampSelectTeam>,
    pub rerolls_remaining: i32,
    pub their_team: Vec<ChampSelectTeam>,
    pub timer: Timer,
    pub trades: Vec<Trade>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct ChampSelectSummoner {
    pub acting_background_animation_state: String,
    pub active_action_type: String,
    pub are_summoner_actions_complete: bool,
    pub assigned_position: String,
    pub ban_intent_square_portrat_path: String,
    pub cell_id: i32,
    pub champion_icon_style: String,
    pub champion_id: i32,
    pub champion_name: String,
    pub current_champion_vote_percent_integer: i32,
    pub is_acting_now: bool,
    pub is_done_picking: bool,
    pub is_on_players_team: bool,
    pub is_pick_intenting: bool,
    pub is_placeholder: bool,
    pub is_self: bool,
    pub name_visibility_type: String,
    pub obfuscated_puuid: String,
    pub obfuscated_summoner_id: i64,
    pub pick_sniped_class: String,
    pub puuid: String,
    pub should_show_acting_bar: bool,
    pub should_show_ban_intent_icon: bool,
    pub should_show_expanded: bool,
    pub should_show_ring_animations: bool,
    pub should_show_selected_skin: bool,
    pub should_show_spells: bool,
    pub show_muted: bool,
    pub show_swaps: bool,
    pub show_trades: bool,
    pub skin_id: i32,
    pub skin_splash_path: String,
    pub slot_id: i32,
    pub spell1_icon_path: String,
    pub spell2_icon_path: String,
    pub status_message_key: String,
    pub summoner_id: i64,
    pub swap_id: i32,
    pub trade_id: i32,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct Trade {
    pub cell_id: i32,
    pub id: i32,
    pub state: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct ChampSelectTeam {
    pub assigned_position: String,
    pub cell_id: i32,
    pub champion_id: i32,
    pub champion_pick_intent: i32,
    pub entitled_feature_type: String,
    pub name_visibility_type: String,
    pub obfuscated_puuid: String,
    pub obfuscated_summoner_id: i64,
    pub player_type: String,
    pub puuid: String,
    pub selected_skin_id: i32,
    pub spell1_id: i32,
    pub spell2_id: i32,
    pub summoner_id: i64,
    pub team: i32,
    pub ward_skin_id: i32,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct EntitledFeatureState {
    pub additional_rerolls: i32,
    pub unlocked_skin_ids: Vec<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct BenchChampion {
    pub champion_id: i32,
    pub is_priority: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct Bans {
    pub my_team_bans: Vec<i32>,
    pub num_bans: i32,
    pub their_team_bans: Vec<i32>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct GridChamp {
    pub disabled: bool,
    pub free_to_play: bool,
    pub free_to_play_for_queue: bool,
    pub id: i32,
    pub loyalty_reward: bool,
    pub mastery_level: i32,
    pub mastery_points: i32,
    pub name: String,
    pub owned: bool,
    pub positions_favorited: Vec<serde_json::Value>,
    pub rented: bool,
    pub roles: Vec<serde_json::Value>,
    pub selection_status: SelectionStatus,
    pub square_portrait_path: String,
    pub xbox_g_p_reward: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct SelectionStatus {
    pub ban_intented: bool,
    pub ban_intented_by_me: bool,
    pub is_banned: bool,
    pub pick_intented: bool,
    pub pick_intented_by_me: bool,
    pub pick_intented_position: String,
    pub picked_by_other_or_banned: bool,
    pub selected_by_me: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct Timer {
    pub adjusted_time_left_in_phase: i64,
    pub internal_now_in_epoch_ms: i64,
    pub is_infinite: bool,
    pub phase: String,
    pub total_time_in_phase: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct ChatDetails {
    pub chat_room_name: String,
    pub chat_room_password: String,
    pub multi_user_chat_jwt: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct Action {
    pub actor_cell_id: i32,
    pub champion_id: i32,
    pub completed: bool,
    pub id: i32,
    pub is_ally_action: bool,
    pub is_in_progress: bool,
    pub pick_turn: i32,
    pub r#type: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct OngoingTrade {
    pub id: i32,
    pub initiated_by_local_player: bool,
    pub other_summoner_index: i32,
    pub requester_champion_name: String,
    pub requester_champion_splash_path: String,
    pub responder_champion_name: String,
    pub responder_index: i32,
    pub state: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct CarouselSkins {
    pub champion_id: i32,
    pub child_skins: Vec<ChildSkin>,
    pub chroma_preview_path: Option<String>,
    pub disabled: bool,
    pub emblems: Vec<Emblem>,
    pub group_splash: String,
    pub id: i32,
    pub is_base: bool,
    pub is_champion_unlocked: bool,
    pub name: String,
    pub ownership: Ownership,
    pub product_type: Option<serde_json::Value>,
    pub rarity_gem_path: String,
    pub skin_augments: SkinAugments,
    pub splash_path: String,
    pub splash_video_path: Option<String>,
    pub still_obtainable: bool,
    pub tile_path: String,
    pub unlocked: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct Emblem {
    pub emblem_path: EmblemPath,
    pub name: String,
    pub positions: Positions,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct Positions {
    pub horizontal: String,
    pub vertical: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct EmblemPath {
    pub large: String,
    pub small: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct ChildSkin {
    pub champion_id: i32,
    pub chroma_preview_path: String,
    pub colors: Vec<String>,
    pub disabled: bool,
    pub id: i32,
    pub is_base: bool,
    pub is_champion_unlocked: bool,
    pub name: String,
    pub ownership: Ownership,
    pub parent_skin_id: i32,
    pub short_name: String,
    pub skin_augments: SkinAugments,
    pub splash_path: String,
    pub splash_video_path: Option<String>,
    pub stage: i32,
    pub still_obtainable: bool,
    pub tile_path: String,
    pub unlocked: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct Ownership {
    pub loyalty_reward: bool,
    pub owned: bool,
    pub rental: Rental,
    pub xbox_gp_reward: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct Rental {
    pub rented: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct SkinAugments {}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct MySelection {
    pub assigned_position: String,
    pub cell_id: i32,
    pub champion_id: i32,
    pub champion_pick_intent: i32,
    pub name_visibility_type: String,
    pub obfuscated_puuid: String,
    pub obfuscated_summoner_id: i64,
    pub puuid: String,
    pub selected_skin_id: i32,
    pub spell1_id: i32,
    pub spell2_id: i32,
    pub summoner_id: i64,
    pub team: i32,
    pub ward_skin_id: i32,
}
