use serde::Deserialize;
use serde::Serialize;

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SgpMatchHistoryLol {
    pub games: Vec<Games>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Games {
    pub metadata: Metadata,
    pub json: Json,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Metadata {
    pub product: String,
    pub tags: Vec<String>,
    pub participants: Vec<String>,
    pub timestamp: String,
    #[serde(rename = "data_version")]
    pub data_version: String,
    #[serde(rename = "info_type")]
    pub info_type: String,
    #[serde(rename = "match_id")]
    pub match_id: String,
    pub private: bool,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Json {
    pub end_of_game_result: String,
    pub game_creation: i64,
    pub game_duration: i64,
    pub game_end_timestamp: i64,
    pub game_id: i64,
    pub game_mode: String,
    pub game_name: String,
    pub game_start_timestamp: i64,
    pub game_type: String,
    pub game_version: String,
    pub map_id: i64,
    pub participants: Vec<Participant>,
    pub platform_id: String,
    pub queue_id: i64,
    pub season_id: i64,
    pub teams: Vec<Team>,
    pub tournament_code: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Participant {
    #[serde(rename = "PlayerScore0")]
    pub player_score0: f64,
    #[serde(rename = "PlayerScore1")]
    pub player_score1: f64,
    #[serde(rename = "PlayerScore10")]
    pub player_score10: f64,
    #[serde(rename = "PlayerScore11")]
    pub player_score11: f64,
    #[serde(rename = "PlayerScore2")]
    pub player_score2: f64,
    #[serde(rename = "PlayerScore3")]
    pub player_score3: f64,
    #[serde(rename = "PlayerScore4")]
    pub player_score4: f64,
    #[serde(rename = "PlayerScore5")]
    pub player_score5: f64,
    #[serde(rename = "PlayerScore6")]
    pub player_score6: f64,
    #[serde(rename = "PlayerScore7")]
    pub player_score7: f64,
    #[serde(rename = "PlayerScore8")]
    pub player_score8: f64,
    #[serde(rename = "PlayerScore9")]
    pub player_score9: f64,
    pub all_in_pings: i64,
    pub assist_me_pings: i64,
    pub assists: i64,
    pub baron_kills: i64,
    pub basic_pings: i64,
    pub challenges: Option<Challenges>,
    pub champ_experience: i64,
    pub champ_level: i64,
    pub champion_id: i64,
    pub champion_name: String,
    pub champion_transform: i64,
    pub command_pings: i64,
    pub consumables_purchased: i64,
    pub damage_dealt_to_buildings: i64,
    pub damage_dealt_to_epic_monsters: i64,
    pub damage_dealt_to_objectives: i64,
    pub damage_dealt_to_turrets: i64,
    pub damage_self_mitigated: i64,
    pub danger_pings: i64,
    pub deaths: i64,
    pub detector_wards_placed: i64,
    pub double_kills: i64,
    pub dragon_kills: i64,
    pub eligible_for_progression: bool,
    pub enemy_missing_pings: i64,
    pub enemy_vision_pings: i64,
    pub first_blood_assist: bool,
    pub first_blood_kill: bool,
    pub first_tower_assist: bool,
    pub first_tower_kill: bool,
    pub game_ended_in_early_surrender: bool,
    pub game_ended_in_surrender: bool,
    pub get_back_pings: i64,
    pub gold_earned: i64,
    pub gold_spent: i64,
    pub hold_pings: i64,
    pub individual_position: String,
    pub inhibitor_kills: i64,
    pub inhibitor_takedowns: i64,
    pub inhibitors_lost: i64,
    pub item0: i64,
    pub item1: i64,
    pub item2: i64,
    pub item3: i64,
    pub item4: i64,
    pub item5: i64,
    pub item6: i64,
    pub items_purchased: i64,
    pub killing_sprees: i64,
    pub kills: i64,
    pub lane: String,
    pub largest_critical_strike: i64,
    pub largest_killing_spree: i64,
    pub largest_multi_kill: i64,
    pub longest_time_spent_living: i64,
    pub magic_damage_dealt: i64,
    pub magic_damage_dealt_to_champions: i64,
    pub magic_damage_taken: i64,
    pub missions: Missions,
    pub need_vision_pings: i64,
    pub neutral_minions_killed: i64,
    pub nexus_kills: i64,
    pub nexus_lost: i64,
    pub nexus_takedowns: i64,
    pub objectives_stolen: i64,
    pub objectives_stolen_assists: i64,
    pub on_my_way_pings: i64,
    pub participant_id: i64,
    pub penta_kills: i64,
    pub perks: Perks,
    pub physical_damage_dealt: i64,
    pub physical_damage_dealt_to_champions: i64,
    pub physical_damage_taken: i64,
    pub placement: i64,
    pub player_augment1: i64,
    pub player_augment2: i64,
    pub player_augment3: i64,
    pub player_augment4: i64,
    pub player_augment5: i64,
    pub player_augment6: i64,
    pub player_subteam_id: i64,
    pub profile_icon: i64,
    pub push_pings: i64,
    pub puuid: String,
    pub quadra_kills: i64,
    pub retreat_pings: i64,
    pub riot_id_game_name: String,
    pub riot_id_tagline: String,
    pub role: String,
    pub sight_wards_bought_in_game: i64,
    #[serde(rename = "spell1Casts")]
    pub spell1casts: i64,
    #[serde(rename = "spell1Id")]
    pub spell1id: i64,
    #[serde(rename = "spell2Casts")]
    pub spell2casts: i64,
    #[serde(rename = "spell2Id")]
    pub spell2id: i64,
    #[serde(rename = "spell3Casts")]
    pub spell3casts: i64,
    #[serde(rename = "spell4Casts")]
    pub spell4casts: i64,
    pub subteam_placement: i64,
    #[serde(rename = "summoner1Casts")]
    pub summoner1casts: i64,
    #[serde(rename = "summoner2Casts")]
    pub summoner2casts: i64,
    pub summoner_id: i64,
    pub summoner_level: i64,
    pub summoner_name: String,
    pub team_early_surrendered: bool,
    pub team_id: i64,
    pub team_position: String,
    #[serde(rename = "timeCCingOthers")]
    pub time_ccing_others: i64,
    pub time_played: i64,
    pub total_ally_jungle_minions_killed: i64,
    pub total_damage_dealt: i64,
    pub total_damage_dealt_to_champions: i64,
    pub total_damage_shielded_on_teammates: i64,
    pub total_damage_taken: i64,
    pub total_enemy_jungle_minions_killed: i64,
    pub total_heal: i64,
    pub total_heals_on_teammates: i64,
    pub total_minions_killed: i64,
    #[serde(rename = "totalTimeCCDealt")]
    pub total_time_ccdealt: i64,
    pub total_time_spent_dead: i64,
    pub total_units_healed: i64,
    pub triple_kills: i64,
    pub true_damage_dealt: i64,
    pub true_damage_dealt_to_champions: i64,
    pub true_damage_taken: i64,
    pub turret_kills: i64,
    pub turret_takedowns: i64,
    pub turrets_lost: i64,
    pub unreal_kills: i64,
    pub vision_cleared_pings: i64,
    pub vision_score: i64,
    pub vision_wards_bought_in_game: i64,
    pub wards_killed: i64,
    pub wards_placed: i64,
    pub win: bool,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Challenges {
    #[serde(rename = "12AssistStreakCount")]
    pub n12assist_streak_count: f64,
    #[serde(rename = "HealFromMapSources")]
    pub heal_from_map_sources: f64,
    #[serde(rename = "InfernalScalePickup")]
    pub infernal_scale_pickup: f64,
    #[serde(rename = "SWARM_DefeatAatrox")]
    pub swarm_defeat_aatrox: f64,
    #[serde(rename = "SWARM_DefeatBriar")]
    pub swarm_defeat_briar: f64,
    #[serde(rename = "SWARM_DefeatMiniBosses")]
    pub swarm_defeat_mini_bosses: f64,
    #[serde(rename = "SWARM_EvolveWeapon")]
    pub swarm_evolve_weapon: f64,
    #[serde(rename = "SWARM_Have3Passives")]
    pub swarm_have3passives: f64,
    #[serde(rename = "SWARM_KillEnemy")]
    pub swarm_kill_enemy: f64,
    #[serde(rename = "SWARM_PickupGold")]
    pub swarm_pickup_gold: f64,
    #[serde(rename = "SWARM_ReachLevel50")]
    pub swarm_reach_level50: f64,
    #[serde(rename = "SWARM_Survive15Min")]
    pub swarm_survive15min: f64,
    #[serde(rename = "SWARM_WinWith5EvolvedWeapons")]
    pub swarm_win_with5evolved_weapons: f64,
    pub ability_uses: f64,
    #[serde(rename = "acesBefore15Minutes")]
    pub aces_before15minutes: f64,
    pub allied_jungle_monster_kills: f64,
    pub baron_takedowns: f64,
    pub blast_cone_opposite_opponent_count: f64,
    pub bounty_gold: f64,
    pub buffs_stolen: f64,
    pub complete_support_quest_in_time: f64,
    pub control_ward_time_coverage_in_river_or_enemy_half: Option<f64>,
    pub control_wards_placed: f64,
    pub damage_per_minute: f64,
    pub damage_taken_on_team_percentage: f64,
    pub danced_with_rift_herald: f64,
    pub deaths_by_enemy_champs: f64,
    pub dodge_skill_shots_small_window: f64,
    pub double_aces: f64,
    pub dragon_takedowns: f64,
    pub early_laning_phase_gold_exp_advantage: Option<f64>,
    pub effective_heal_and_shielding: f64,
    pub elder_dragon_kills_with_opposing_soul: f64,
    pub elder_dragon_multikills: f64,
    pub enemy_champion_immobilizations: f64,
    pub enemy_jungle_monster_kills: f64,
    pub epic_monster_kills_near_enemy_jungler: f64,
    #[serde(rename = "epicMonsterKillsWithin30SecondsOfSpawn")]
    pub epic_monster_kills_within30seconds_of_spawn: f64,
    pub epic_monster_steals: f64,
    pub epic_monster_stolen_without_smite: f64,
    pub first_turret_killed: f64,
    pub first_turret_killed_time: Option<f64>,
    pub fist_bump_participation: f64,
    pub flawless_aces: f64,
    pub full_team_takedown: f64,
    pub game_length: f64,
    pub get_takedowns_in_all_lanes_early_jungle_as_laner: Option<f64>,
    pub gold_per_minute: f64,
    pub had_open_nexus: f64,
    pub immobilize_and_kill_with_ally: f64,
    pub initial_buff_count: f64,
    pub initial_crab_count: f64,
    #[serde(rename = "jungleCsBefore10Minutes")]
    pub jungle_cs_before10minutes: f64,
    pub jungler_takedowns_near_damaged_epic_monster: f64,
    pub k_turrets_destroyed_before_plates_fall: f64,
    pub kda: f64,
    pub kill_after_hidden_with_ally: f64,
    pub kill_participation: Option<f64>,
    pub killed_champ_took_full_team_damage_survived: f64,
    pub killing_sprees: f64,
    pub kills_near_enemy_turret: f64,
    pub kills_on_other_lanes_early_jungle_as_laner: Option<f64>,
    pub kills_on_recently_healed_by_aram_pack: f64,
    pub kills_under_own_turret: f64,
    pub kills_with_help_from_epic_monster: f64,
    pub knock_enemy_into_team_and_kill: f64,
    pub land_skill_shots_early_game: f64,
    #[serde(rename = "laneMinionsFirst10Minutes")]
    pub lane_minions_first10minutes: f64,
    pub laning_phase_gold_exp_advantage: Option<f64>,
    pub legendary_count: f64,
    pub legendary_item_used: Vec<f64>,
    pub lost_an_inhibitor: f64,
    pub max_cs_advantage_on_lane_opponent: Option<f64>,
    pub max_kill_deficit: f64,
    pub max_level_lead_lane_opponent: Option<f64>,
    pub mejais_full_stack_in_time: f64,
    pub more_enemy_jungle_than_opponent: f64,
    pub multi_kill_one_spell: f64,
    pub multi_turret_rift_herald_count: f64,
    pub multikills: f64,
    pub multikills_after_aggressive_flash: f64,
    #[serde(rename = "outerTurretExecutesBefore10Minutes")]
    pub outer_turret_executes_before10minutes: f64,
    pub outnumbered_kills: f64,
    pub outnumbered_nexus_kill: f64,
    pub perfect_dragon_souls_taken: f64,
    pub perfect_game: f64,
    pub pick_kill_with_ally: f64,
    pub played_champ_select_position: Option<f64>,
    pub poro_explosions: f64,
    pub quick_cleanse: f64,
    pub quick_first_turret: f64,
    pub quick_solo_kills: f64,
    pub rift_herald_takedowns: f64,
    pub save_ally_from_death: f64,
    pub scuttle_crab_kills: f64,
    pub skillshots_dodged: f64,
    pub skillshots_hit: f64,
    pub snowballs_hit: f64,
    pub solo_baron_kills: f64,
    pub solo_kills: f64,
    pub stealth_wards_placed: f64,
    pub survived_single_digit_hp_count: f64,
    pub survived_three_immobilizes_in_fight: f64,
    pub takedown_on_first_turret: f64,
    pub takedowns: f64,
    pub takedowns_after_gaining_level_advantage: f64,
    pub takedowns_before_jungle_minion_spawn: f64,
    #[serde(rename = "takedownsFirstXMinutes")]
    pub takedowns_first_xminutes: f64,
    pub takedowns_in_alcove: f64,
    pub takedowns_in_enemy_fountain: f64,
    pub team_baron_kills: f64,
    pub team_damage_percentage: Option<f64>,
    pub team_elder_dragon_kills: f64,
    pub team_rift_herald_kills: f64,
    pub took_large_damage_survived: f64,
    pub turret_plates_taken: f64,
    pub turret_takedowns: f64,
    pub turrets_taken_with_rift_herald: f64,
    #[serde(rename = "twentyMinionsIn3SecondsCount")]
    pub twenty_minions_in3seconds_count: f64,
    pub two_wards_one_sweeper_count: f64,
    pub unseen_recalls: f64,
    pub vision_score_advantage_lane_opponent: Option<f64>,
    pub vision_score_per_minute: f64,
    pub void_monster_kill: f64,
    pub ward_takedowns: f64,
    #[serde(rename = "wardTakedownsBefore20M")]
    pub ward_takedowns_before20m: f64,
    pub wards_guarded: f64,
    pub earliest_dragon_takedown: Option<f64>,
    pub jungler_kills_early_jungle: Option<f64>,
    pub kills_on_laners_early_jungle_as_jungler: Option<f64>,
    pub solo_turrets_lategame: Option<f64>,
    pub faster_support_quest_completion: Option<f64>,
    pub highest_champion_damage: Option<f64>,
    pub highest_ward_kills: Option<f64>,
    pub baron_buff_gold_advantage_over_threshold: Option<f64>,
    pub earliest_baron: Option<f64>,
    pub highest_crowd_control_score: Option<f64>,
    pub shortest_time_to_ace_from_first_takedown: Option<f64>,
    pub had_afk_teammate: Option<f64>,
    pub teleport_takedowns: Option<f64>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Missions {
    #[serde(rename = "ActMission_S1_A2_ArenaRoundsWon")]
    pub act_mission_s1_a2_arena_rounds_won: i64,
    #[serde(rename = "ActMission_S1_A2_BloodyPetalsCollected")]
    pub act_mission_s1_a2_bloody_petals_collected: i64,
    #[serde(rename = "ActMission_S1_A2_FeatsOfStrength")]
    pub act_mission_s1_a2_feats_of_strength: i64,
    #[serde(rename = "DemonsHand_MissionPointsA")]
    pub demons_hand_mission_points_a: i64,
    #[serde(rename = "DemonsHand_MissionPointsB")]
    pub demons_hand_mission_points_b: i64,
    #[serde(rename = "DemonsHand_MissionPointsC")]
    pub demons_hand_mission_points_c: i64,
    #[serde(rename = "DemonsHand_MissionPointsD")]
    pub demons_hand_mission_points_d: i64,
    #[serde(rename = "DemonsHand_MissionPointsE")]
    pub demons_hand_mission_points_e: i64,
    #[serde(rename = "DemonsHand_MissionPointsF")]
    pub demons_hand_mission_points_f: i64,
    #[serde(rename = "Event_2025LR_StructuresEpicMonsters")]
    pub event_2025lr_structures_epic_monsters: i64,
    #[serde(rename = "Event_ARAM_Docks")]
    pub event_aram_docks: i64,
    #[serde(rename = "Event_ARAM_Hexgates")]
    pub event_aram_hexgates: i64,
    #[serde(rename = "Event_Brawl_Jungle")]
    pub event_brawl_jungle: i64,
    #[serde(rename = "Event_Brawl_Minions")]
    pub event_brawl_minions: i64,
    #[serde(rename = "Event_S1_A1_AprilFools_Dragon")]
    pub event_s1_a1_april_fools_dragon: i64,
    #[serde(rename = "Event_S1_A1_AprilFools_Snowball")]
    pub event_s1_a1_april_fools_snowball: i64,
    #[serde(rename = "Event_S1_A2_AprilFools_Dragon")]
    pub event_s1_a2_april_fools_dragon: i64,
    #[serde(rename = "Event_S1_A2_AprilFools_Garen_Play")]
    pub event_s1_a2_april_fools_garen_play: i64,
    #[serde(rename = "Event_S1_A2_AprilFools_Garen_Takedown")]
    pub event_s1_a2_april_fools_garen_takedown: i64,
    #[serde(rename = "Event_S1_A2_AprilFools_Snowball")]
    pub event_s1_a2_april_fools_snowball: i64,
    #[serde(rename = "Event_S1_A2_Arena_BraveryChampions")]
    pub event_s1_a2_arena_bravery_champions: i64,
    #[serde(rename = "Event_S1_A2_Arena_NoxianChampions")]
    pub event_s1_a2_arena_noxian_champions: i64,
    #[serde(rename = "Event_S1_A2_Arena_ReviveAllies")]
    pub event_s1_a2_arena_revive_allies: i64,
    #[serde(rename = "Event_S1_A2_Esports_TakedownEpicMonstersSingleGame")]
    pub event_s1_a2_esports_takedown_epic_monsters_single_game: i64,
    #[serde(rename = "Event_S1_A2_Mordekaiser")]
    pub event_s1_a2_mordekaiser: i64,
    #[serde(rename = "Event_S2A2Champ_DamageAbilities")]
    pub event_s2a2champ_damage_abilities: i64,
    #[serde(rename = "Event_S2A2Champ_DamageAutos")]
    pub event_s2a2champ_damage_autos: i64,
    #[serde(rename = "Event_S2A2_Exalted")]
    pub event_s2a2_exalted: i64,
    #[serde(rename = "Event_S2A2_MV")]
    pub event_s2a2_mv: i64,
    #[serde(rename = "Event_S2A2_PetalPoints")]
    pub event_s2a2_petal_points: i64,
    #[serde(rename = "HoL_ChampionsDamagedWhileHidden")]
    pub ho_l_champions_damaged_while_hidden: i64,
    #[serde(rename = "HoL_ControlWardsKilled")]
    pub ho_l_control_wards_killed: i64,
    #[serde(rename = "HoL_Elite_AsheCrystalArrowTakedowns")]
    pub ho_l_elite_ashe_crystal_arrow_takedowns: i64,
    #[serde(rename = "HoL_Elite_AsheHawkshotChampsRevealed")]
    pub ho_l_elite_ashe_hawkshot_champs_revealed: i64,
    #[serde(rename = "HoL_Elite_EzrealEssenceFluxDetonated")]
    pub ho_l_elite_ezreal_essence_flux_detonated: i64,
    #[serde(rename = "HoL_Elite_EzrealTrueshotBarrageMultiHit")]
    pub ho_l_elite_ezreal_trueshot_barrage_multi_hit: i64,
    #[serde(rename = "HoL_Elite_KaiSaAbilitiesUpgraded")]
    pub ho_l_elite_kai_sa_abilities_upgraded: i64,
    #[serde(rename = "HoL_Elite_KaiSaKillerInstinctKills")]
    pub ho_l_elite_kai_sa_killer_instinct_kills: i64,
    #[serde(rename = "HoL_Elite_LucianCullingHits")]
    pub ho_l_elite_lucian_culling_hits: i64,
    #[serde(rename = "HoL_Elite_LucianPiercingLightMultiHit")]
    pub ho_l_elite_lucian_piercing_light_multi_hit: i64,
    #[serde(rename = "HoL_Elite_VayneCondemnStun")]
    pub ho_l_elite_vayne_condemn_stun: i64,
    #[serde(rename = "HoL_Elite_VayneTumbleDodge")]
    pub ho_l_elite_vayne_tumble_dodge: i64,
    #[serde(rename = "HoL_EnemyTakedownUnderTower")]
    pub ho_l_enemy_takedown_under_tower: i64,
    #[serde(rename = "HoL_FightsSurvivedWhileLowHealth")]
    pub ho_l_fights_survived_while_low_health: i64,
    #[serde(rename = "HoL_HiddenEnemiesDamaged")]
    pub ho_l_hidden_enemies_damaged: i64,
    #[serde(rename = "HoL_JungleCampsStolen")]
    pub ho_l_jungle_camps_stolen: i64,
    #[serde(rename = "HoL_KillsWhileLowHealth")]
    pub ho_l_kills_while_low_health: i64,
    #[serde(rename = "HoL_OutnumberedTakedowns")]
    pub ho_l_outnumbered_takedowns: i64,
    #[serde(rename = "HoL_ShutdownGoldCollected")]
    pub ho_l_shutdown_gold_collected: i64,
    #[serde(rename = "HoL_SoloKills")]
    pub ho_l_solo_kills: i64,
    #[serde(rename = "HoL_TurretsTakenWithinMinutes")]
    pub ho_l_turrets_taken_within_minutes: i64,
    #[serde(rename = "Missions_BXP_EarnedPerGame")]
    pub missions_bxp_earned_per_game: i64,
    #[serde(rename = "Missions_CannonMinionsKilled")]
    pub missions_cannon_minions_killed: i64,
    #[serde(rename = "Missions_ChampionTakedownsWhileGhosted")]
    pub missions_champion_takedowns_while_ghosted: i64,
    #[serde(rename = "Missions_ChampionTakedownsWithIgnite")]
    pub missions_champion_takedowns_with_ignite: i64,
    #[serde(rename = "Missions_ChampionsHitWithAbilitiesEarlyGame")]
    pub missions_champions_hit_with_abilities_early_game: i64,
    #[serde(rename = "Missions_ChampionsKilled")]
    pub missions_champions_killed: i64,
    #[serde(rename = "Missions_CreepScore")]
    pub missions_creep_score: i64,
    #[serde(rename = "Missions_CreepScoreBy10Minutes")]
    pub missions_creep_score_by10minutes: i64,
    #[serde(rename = "Missions_Crepe_DamageDealtSpeedZone")]
    pub missions_crepe_damage_dealt_speed_zone: i64,
    #[serde(rename = "Missions_Crepe_SnowballLanded")]
    pub missions_crepe_snowball_landed: i64,
    #[serde(rename = "Missions_Crepe_TakedownsWithInhibBuff")]
    pub missions_crepe_takedowns_with_inhib_buff: i64,
    #[serde(rename = "Missions_DamageToChampsWithItems")]
    pub missions_damage_to_champs_with_items: i64,
    #[serde(rename = "Missions_DamageToStructures")]
    pub missions_damage_to_structures: i64,
    #[serde(rename = "Missions_DestroyPlants")]
    pub missions_destroy_plants: i64,
    #[serde(rename = "Missions_DominationRune")]
    pub missions_domination_rune: i64,
    #[serde(rename = "Missions_GoldFromStructuresDestroyed")]
    pub missions_gold_from_structures_destroyed: i64,
    #[serde(rename = "Missions_GoldFromTurretPlatesTaken")]
    pub missions_gold_from_turret_plates_taken: i64,
    #[serde(rename = "Missions_GoldPerMinute")]
    pub missions_gold_per_minute: i64,
    #[serde(rename = "Missions_HealingFromLevelObjects")]
    pub missions_healing_from_level_objects: i64,
    #[serde(rename = "Missions_HexgatesUsed")]
    pub missions_hexgates_used: i64,
    #[serde(rename = "Missions_ImmobilizeChampions")]
    pub missions_immobilize_champions: i64,
    #[serde(rename = "Missions_InspirationRune")]
    pub missions_inspiration_rune: i64,
    #[serde(rename = "Missions_LegendaryItems")]
    pub missions_legendary_items: i64,
    #[serde(rename = "Missions_MinionsKilled")]
    pub missions_minions_killed: i64,
    #[serde(rename = "Missions_PeriodicDamage")]
    pub missions_periodic_damage: i64,
    #[serde(rename = "Missions_PlaceUsefulControlWards")]
    pub missions_place_useful_control_wards: i64,
    #[serde(rename = "Missions_PlaceUsefulWards")]
    pub missions_place_useful_wards: i64,
    #[serde(rename = "Missions_PorosFed")]
    pub missions_poros_fed: i64,
    #[serde(rename = "Missions_PrecisionRune")]
    pub missions_precision_rune: i64,
    #[serde(rename = "Missions_ResolveRune")]
    pub missions_resolve_rune: i64,
    #[serde(rename = "Missions_SnowballsHit")]
    pub missions_snowballs_hit: i64,
    #[serde(rename = "Missions_SorceryRune")]
    pub missions_sorcery_rune: i64,
    #[serde(rename = "Missions_TakedownBaronsElderDragons")]
    pub missions_takedown_barons_elder_dragons: i64,
    #[serde(rename = "Missions_TakedownDragons")]
    pub missions_takedown_dragons: i64,
    #[serde(rename = "Missions_TakedownEpicMonsters")]
    pub missions_takedown_epic_monsters: i64,
    #[serde(rename = "Missions_TakedownEpicMonstersSingleGame")]
    pub missions_takedown_epic_monsters_single_game: i64,
    #[serde(rename = "Missions_TakedownGold")]
    pub missions_takedown_gold: i64,
    #[serde(rename = "Missions_TakedownStructures")]
    pub missions_takedown_structures: i64,
    #[serde(rename = "Missions_TakedownWards")]
    pub missions_takedown_wards: i64,
    #[serde(rename = "Missions_TakedownsAfterExhausting")]
    pub missions_takedowns_after_exhausting: i64,
    #[serde(rename = "Missions_TakedownsAfterTeleporting")]
    pub missions_takedowns_after_teleporting: i64,
    #[serde(rename = "Missions_TakedownsBefore15Min")]
    pub missions_takedowns_before15min: i64,
    #[serde(rename = "Missions_TakedownsUnderTurret")]
    pub missions_takedowns_under_turret: i64,
    #[serde(rename = "Missions_TakedownsWithHelpFromMonsters")]
    pub missions_takedowns_with_help_from_monsters: i64,
    #[serde(rename = "Missions_TimeSpentActivelyPlaying")]
    pub missions_time_spent_actively_playing: i64,
    #[serde(rename = "Missions_TotalGold")]
    pub missions_total_gold: i64,
    #[serde(rename = "Missions_TrueDamageToStructures")]
    pub missions_true_damage_to_structures: i64,
    #[serde(rename = "Missions_TurretPlatesDestroyed")]
    pub missions_turret_plates_destroyed: i64,
    #[serde(rename = "Missions_TwoChampsKilledWithSameAbility")]
    pub missions_two_champs_killed_with_same_ability: i64,
    #[serde(rename = "Missions_VoidMitesSummoned")]
    pub missions_void_mites_summoned: i64,
    #[serde(rename = "PlayerScore0")]
    pub player_score0: f64,
    #[serde(rename = "PlayerScore1")]
    pub player_score1: f64,
    #[serde(rename = "PlayerScore10")]
    pub player_score10: f64,
    #[serde(rename = "PlayerScore11")]
    pub player_score11: f64,
    #[serde(rename = "PlayerScore2")]
    pub player_score2: f64,
    #[serde(rename = "PlayerScore3")]
    pub player_score3: f64,
    #[serde(rename = "PlayerScore4")]
    pub player_score4: f64,
    #[serde(rename = "PlayerScore5")]
    pub player_score5: f64,
    #[serde(rename = "PlayerScore6")]
    pub player_score6: f64,
    #[serde(rename = "PlayerScore7")]
    pub player_score7: f64,
    #[serde(rename = "PlayerScore8")]
    pub player_score8: f64,
    #[serde(rename = "PlayerScore9")]
    pub player_score9: f64,
    #[serde(rename = "S3A1_Event_DoombotsTakenDownBefore5")]
    pub s3a1_event_doombots_taken_down_before5: i64,
    #[serde(rename = "S3A1_PlayAsDemaciansOrAgainstNoxians")]
    pub s3a1_play_as_demacians_or_against_noxians: i64,
    #[serde(rename = "S3A1_Takedowns")]
    pub s3a1_takedowns: i64,
    #[serde(rename = "S3A2_PrismaticAug")]
    pub s3a2_prismatic_aug: i64,
    #[serde(rename = "SeasonalMissions_TakedownAtakhan")]
    pub seasonal_missions_takedown_atakhan: i64,
    #[serde(rename = "WeeklyMission_S2_DamagingAbilities")]
    pub weekly_mission_s2_damaging_abilities: i64,
    #[serde(rename = "WeeklyMission_S2_FeatsOfStrength")]
    pub weekly_mission_s2_feats_of_strength: i64,
    #[serde(rename = "WeeklyMission_S2_SpiritPetals")]
    pub weekly_mission_s2_spirit_petals: i64,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Perks {
    pub stat_perks: StatPerks,
    pub styles: Vec<Style>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct StatPerks {
    pub defense: i64,
    pub flex: i64,
    pub offense: i64,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Style {
    pub description: String,
    pub selections: Vec<Selection>,
    pub style: i64,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Selection {
    pub perk: i64,
    pub var1: i64,
    pub var2: i64,
    pub var3: i64,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Team {
    pub bans: Vec<Ban>,
    pub feats: Feats,
    pub objectives: Objectives,
    pub team_id: i64,
    pub win: bool,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Ban {
    pub champion_id: i64,
    pub pick_turn: i64,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Feats {
    #[serde(rename = "EPIC_MONSTER_KILL")]
    pub epic_monster_kill: EpicMonsterKill,
    #[serde(rename = "FIRST_BLOOD")]
    pub first_blood: EpicMonsterKill,
    #[serde(rename = "FIRST_TURRET")]
    pub first_turret: EpicMonsterKill,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EpicMonsterKill {
    pub feat_state: i64,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Objectives {
    pub atakhan: Atakhan,
    pub baron: Atakhan,
    pub champion: Atakhan,
    pub dragon: Atakhan,
    pub horde: Atakhan,
    pub inhibitor: Atakhan,
    pub rift_herald: Atakhan,
    pub tower: Atakhan,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Atakhan {
    pub first: bool,
    pub kills: i64,
}
