// types generated by ai

use crate::shared::{http_api::league_client::httpclient::HttpClient, types::champ_select::*};
use crate::utils::error::http_error::HttpError;
use serde::Serialize;

pub struct ChampSelectHttpApi {
    client: HttpClient,
}

impl ChampSelectHttpApi {
    pub fn new(client: HttpClient) -> Self {
        Self { client }
    }

    // -------------------------
    // 基础请求
    // -------------------------

    pub async fn get_session(&self) -> Result<ChampSelectSession, HttpError> {
        let url = "/lol-champ-select/v1/session";
        self.client.get(&url).await
    }

    pub async fn get_all_grid_champs(&self) -> Result<Vec<GridChamp>, HttpError> {
        let url = "/lol-champ-select/v1/all-grid-champions";
        self.client.get(&url).await
    }

    // -------------------------
    // Actions
    // -------------------------

    pub async fn action<T: Serialize>(
        &self,
        action_id: impl ToString,
        data: &T,
    ) -> Result<(), HttpError> {
        let url = format!(
            "/lol-champ-select/v1/session/actions/{}",
            action_id.to_string()
        );
        self.client.patch(&url, Some(&data)).await
    }

    pub async fn pick_or_ban(
        &self,
        champion_id: i32,
        completed: bool,
        action_type: &str, // "pick" | "ban"
        action_id: i32,
    ) -> Result<(), HttpError> {
        #[derive(Serialize)]
        struct ActionBody<'a> {
            champion_id: i32,
            completed: bool,
            #[serde(rename = "type")]
            action_type: &'a str,
        }
        let data = ActionBody {
            champion_id,
            completed,
            action_type,
        };
        self.action(action_id, &data).await
    }

    pub async fn intent_champion(&self, action_id: i32, champion_id: i32) -> Result<(), HttpError> {
        #[derive(Serialize)]
        struct IntentBody {
            champion_id: i32,
        }
        self.action(action_id, &IntentBody { champion_id }).await
    }

    // -------------------------
    // Bench swap
    // -------------------------
    pub async fn bench_swap(&self, champ_id: impl ToString) -> Result<(), HttpError> {
        let url = format!(
            "/lol-champ-select/v1/session/bench/swap/{}",
            champ_id.to_string()
        );
        self.client.post(&url, None::<&()>).await
    }

    // -------------------------
    // Trades
    // -------------------------
    pub async fn decline_trade(&self, trade_id: i32) -> Result<(), HttpError> {
        self.post_trade_action(trade_id, "decline").await
    }

    pub async fn accept_trade(&self, trade_id: i32) -> Result<(), HttpError> {
        self.post_trade_action(trade_id, "accept").await
    }

    pub async fn cancel_trade(&self, trade_id: i32) -> Result<(), HttpError> {
        self.post_trade_action(trade_id, "cancel").await
    }

    pub async fn request_trade(&self, trade_id: i32) -> Result<(), HttpError> {
        self.post_trade_action(trade_id, "request").await
    }

    async fn post_trade_action(&self, trade_id: i32, action: &str) -> Result<(), HttpError> {
        let url = format!(
            "/lol-champ-select/v1/session/trades/{}/{}",
            trade_id, action
        );
        self.client.post(&url, None::<&()>).await
    }

    // -------------------------
    // Swaps
    // -------------------------
    pub async fn accept_swap(&self, id: i32) -> Result<(), HttpError> {
        self.post_swap_action(id, "accept").await
    }

    pub async fn decline_swap(&self, id: i32) -> Result<(), HttpError> {
        self.post_swap_action(id, "decline").await
    }

    pub async fn cancel_swap(&self, id: i32) -> Result<(), HttpError> {
        self.post_swap_action(id, "cancel").await
    }

    pub async fn request_swap(&self, id: i32) -> Result<(), HttpError> {
        self.post_swap_action(id, "request").await
    }

    async fn post_swap_action(&self, id: i32, action: &str) -> Result<(), HttpError> {
        let url = format!("/lol-champ-select/v1/session/swaps/{}/{}", id, action);
        self.client.post(&url, None::<&()>).await
    }

    // -------------------------
    // Info getters
    // -------------------------
    pub async fn get_ongoing_trade(&self) -> Result<OngoingTrade, HttpError> {
        let url = "/lol-champ-select/v1/ongoing-trade";
        self.client.get(&url).await
    }

    pub async fn get_pickable_champ_ids(&self) -> Result<Vec<i32>, HttpError> {
        let url = "/lol-champ-select/v1/pickable-champion-ids";
        self.client.get(&url).await
    }

    pub async fn get_bannable_champ_ids(&self) -> Result<Vec<i32>, HttpError> {
        let url = "/lol-champ-select/v1/bannable-champion-ids";
        self.client.get(&url).await
    }

    pub async fn reroll(&self) -> Result<(), HttpError> {
        let url = "/lol-champ-select/v1/session/my-selection/reroll";
        self.client.post(&url, None::<&()>).await
    }

    pub async fn get_current_champ(&self) -> Result<i32, HttpError> {
        let url = "/lol-champ-select/v1/current-champion";
        self.client.get(&url).await
    }

    pub async fn get_disabled_champions(&self) -> Result<Vec<i32>, HttpError> {
        let url = "/lol-champ-select/v1/disabled-champion-ids";
        self.client.get(&url).await
    }

    pub async fn get_summoner(&self, cell_id: i32) -> Result<ChampSelectSummoner, HttpError> {
        let url = format!("/lol-champ-select/v1/summoners/{}", cell_id);
        self.client.get(&url).await
    }

    pub async fn set_skin(&self, id: i32) -> Result<(), HttpError> {
        #[derive(Serialize)]
        struct Body {
            selected_skin_id: i32,
        }
        let url = "/lol-champ-select/v1/session/my-selection";
        self.client
            .patch(
                &url,
                Some(&Body {
                    selected_skin_id: id,
                }),
            )
            .await
    }

    pub async fn get_carousel_skins(&self) -> Result<Vec<CarouselSkins>, HttpError> {
        self.client
            .get("/lol-champ-select/v1/skin-carousel-skins")
            .await
    }

    pub async fn get_my_selection(&self) -> Result<MySelection, HttpError> {
        self.client
            .get("/lol-champ-select/v1/session/my-selection")
            .await
    }

    pub async fn set_summoner_spells(
        &self,
        data: &SetSummonerSpellsRequest,
    ) -> Result<(), HttpError> {
        self.client
            .patch("/lol-champ-select/v1/session/my-selection", Some(&data))
            .await
    }
}

/// 用于设置召唤师技能的请求体
#[derive(Debug, Serialize)]
pub struct SetSummonerSpellsRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub spell1_id: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub spell2_id: Option<i32>,
}
